### ISSUE TITLE
[Fix] 온보딩 및 로그인 수정

### ISSUE THREAD

**Issue by gitsuhyun** [Good-Moneying/Android#67]
## Issue

이슈 내용: 
로그인 이미지 변경 및 ui 체크
온보딩 ui 수정

## Branch Name

 생성 브랜치 이름 : `fix/auth`

## To-Do List

- 로그인

- [x] 이미지 안깨지게 수정
- [x] 카카오 로그인 버튼 확인

- 온보딩
- [x] 관심사 부분 마지막 라인 간격 맞추기
- [x] 목표 설정 -> 웰컴 스크린 넘어가는 속도 줄이기
- [x] 버튼 간격 확인
- [x] 마지막에 구름 이미지 추가
