### ISSUE TITLE
[Fix] 메인홈

### ISSUE THREAD

**Issue by gitsuhyun** [Good-Moneying/Android#68]
## Issue

이슈 내용: 메인 홈 기능 및 ui 수정

## Branch Name

 생성 브랜치 이름 : `feat/home`

## To-Do List

- [x] 스크랩 api 연동 확인
- [x] 스크랩 비활성/활성 확인 -> 팝업 뜨는지
- [x] 로그인 닉네임 노출
- [x] 온보딩에서 설정한 관심사 뉴스만 노출
- [x] 북마크 확인

- ui 수정
- [x] 에디터 카드 그림자 수정
- [x] 추천해요 그림자, 사진 간격 + 크기, 칩 라운드
- [x] 관심사 코인 -> 금융으로 변동
- [x] 오늘의 단어 : 간격 확인
- [x] tooltip border 수정
