### ISSUE TITLE
기능 피드백

### ISSUE THREAD

**Issue by gitsuhyun** [Good-Moneying/Android#75]
## Issue

이슈 내용: 기능 피드백

## Branch Name

 생성 브랜치 이름 : ``

## To-Do List

- 온보딩 
- [ ] 회원가입 때 닉네임 설정

- 홈
- [ ] 그림자
- [ ] 추천 뉴스 태그 수정 (백엔드)

- 뉴스레터 (에디터)
- [ ] 태그 수정
- [ ] 코멘트 부분 나만 보기 기능 되도록
- [ ] 코멘트 positive negative nothing 바꿔야함

- 생각나누기
- [ ] 퀴즈 전반적으로 모두 수정
- [ ] 그래프 안되면 걍 ui 넣기

- 공통
- [ ] 생각더하기/나누기 나갔을때 화면 홈으로 안가게 해야해..
