### ISSUE TITLE
전시회 전 수정

### ISSUE THREAD

**Issue by gitsuhyun** [Good-Moneying/Android#93]
## Issue

이슈 내용: 전시회 전 수정

## Branch Name

 생성 브랜치 이름 : `exhibition`

## To-Do List

- 계정 관리
- [x] 회원탈퇴
- [x] 로그아웃
- [x] 생일 관련 예외처리 
- [x] 닉네임 중복시 메시지 띄우기

- 기본
- [x] 스플래시
- [x] 앱 아이콘

- 생각 나누기
- [x] 퀴즈 오류 수정
- [x] 설문 API
